GradeCalculator/Models/Course.cs
namespace GradeCalculator.Models
{
	public class Course
	{
		public int Id { get; set; }
		public string CourseCode { get; set; }
		public string CourseTitle { get; set; }
		public double CreditHour { get; set; }
		public string Grade { get; set; }
		public double? GradePoint { get; set; }
	}
}

GradeCalculator/Models/ErrorViewModel.cs
namespace GradeCalculator.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

GradeCalculator/Models/Profile.cs
namespace GradeCalculator.Models
{
	public class Profile
	{
		public int ID { get; set; }
		public string Name { get; set; }
		public List<Semester>? Semesters { get; set; }
	}
}

GradeCalculator/Models/Semester.cs
namespace GradeCalculator.Models
{
	public class Semester
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public int SemesterOrder { get; set; }
		public int Year { get; set; }
		public double? Average { get; set; }
		public double? CGPA { get; set; }
		public double? TotalCreditHour { get; set; }
		public double? TotalGradePoint { get; set; }
		public List<Course>? Courses { get; set; }
	}
}

GradeCalculator/Controllers/GradeController.cs
using GradeCalculator.Repository;
using GradeCalculator.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace GradeCalculator.Controllers
{
	public class GradeController : Controller
	{
		private readonly IGradeCalculatorRepository _GradeCalculatorRepository;
		public GradeController(IGradeCalculatorRepository gradeCalculatorRepository)
		{
			_GradeCalculatorRepository = gradeCalculatorRepository;
		}
		public IActionResult Index(int id)
		{
			GradeViewModel gradeViewModel = new GradeViewModel { profile = _GradeCalculatorRepository.GetProfileById(id) };
			//gradeViewModel.semesters = _GradeCalculatorRepository.ge
			return View(gradeViewModel);
		}
		public ActionResult ViewGrades()
		{
			return View();
		}
		public IActionResult AddSemester(GradeViewModel gradeViewModel)
		{
			//gradeViewModel.profile = _GradeCalculatorRepository.GetProfile(gradeViewModel.profile);
			_GradeCalculatorRepository.AddSemester(gradeViewModel.profile, gradeViewModel.newSemester);
			return View(gradeViewModel);
		}
		public IActionResult AddCourse(GradeViewModel gradeViewModel)
		{
			gradeViewModel.newCourse = _GradeCalculatorRepository.CalculateGradePoint(gradeViewModel.newCourse);
			_GradeCalculatorRepository.AddCourse(gradeViewModel.profile, gradeViewModel.newSemester, gradeViewModel.newCourse);
			return View(gradeViewModel);
		}
		public IActionResult DeleteSemester(GradeViewModel gradeViewModel)
		{
			gradeViewModel.newSemester = _GradeCalculatorRepository.GetSemester(gradeViewModel.newSemester.Id);
			_GradeCalculatorRepository.DeleteSemester(gradeViewModel.newSemester);
			return View(gradeViewModel);
		}
		public IActionResult EditSemester(GradeViewModel gradeViewModel)
		{
			if (gradeViewModel.newSemester.Name == null)
				gradeViewModel.newSemester = _GradeCalculatorRepository.GetSemester(gradeViewModel.newSemester.Id);
			_GradeCalculatorRepository.EditSemester(gradeViewModel.newSemester);
			return View(gradeViewModel);
		}
		public IActionResult EditCourse(GradeViewModel gradeViewModel)
		{
			if(gradeViewModel.newCourse.CourseTitle==null)
				gradeViewModel.newCourse=_GradeCalculatorRepository.GetCourse(gradeViewModel.newCourse.Id);
			gradeViewModel.newCourse = _GradeCalculatorRepository.CalculateGradePoint(gradeViewModel.newCourse);
			_GradeCalculatorRepository.EditCourse(gradeViewModel.profile, gradeViewModel.newSemester, gradeViewModel.newCourse);
			if (gradeViewModel.newSemester.Name == null)
				gradeViewModel.newSemester = _GradeCalculatorRepository.GetSemester(gradeViewModel.newSemester.Id);
			return View(gradeViewModel);
		}
		public IActionResult DeleteCourse(GradeViewModel gradeViewModel)
		{
			gradeViewModel.newCourse = _GradeCalculatorRepository.GetCourse(gradeViewModel.newCourse.Id);
			_GradeCalculatorRepository.DeleteCourse(gradeViewModel.profile, gradeViewModel.newSemester, gradeViewModel.newCourse);
			return View(gradeViewModel);
		}
	}
}

GradeCalculator/Controllers/HomeController.cs
using GradeCalculator.Models;
using GradeCalculator.Repository;
using GradeCalculator.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GradeCalculator.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;
		private readonly IGradeCalculatorRepository _GradeCalculatorRepository;

		public HomeController(ILogger<HomeController> logger, IGradeCalculatorRepository gradeCalculatorRepository)
		{
			_logger = logger;
			_GradeCalculatorRepository = gradeCalculatorRepository;
		}

		public IActionResult Index()
		{
			List<Profile> profiles = _GradeCalculatorRepository.GetProfiles();
			ProfileViewModel profileViewModel = new ProfileViewModel { Profiles = profiles };
			return View(profileViewModel);
		}
		public ActionResult AddProfile(ProfileViewModel profileViewModel)
		{
			_GradeCalculatorRepository.AddProfile(profileViewModel.Profile.Name);
			return Redirect("Index");
		}
		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

GradeCalculator/Views/Grade/AddCourse.cshtml
@using GradeCalculator.ViewModel;
@model GradeViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<a class="btn btn-dark" asp-action="Index" asp-controller="Grade" asp-route-id="@Model.profile.ID">Back</a>
<h2>New Course</h2>
<div class="Course-info">
	<p class="fs-5"><span class="fw-light">Code</span> @Model.newCourse.CourseCode</p>
	<p class="fs-5"><span class="fw-light">Title</span> @Model.newCourse.CourseTitle</p>
	<p class="fs-5"><span class="fw-light">Credit Hour</span> @Model.newCourse.CreditHour</p>
	<p class="fs-5"><span class="fw-light">Grade</span> @Model.newCourse.Grade</p>
	<p class="fs-5"><span class="fw-light">Grade Point</span> @Model.newCourse.GradePoint</p>
</div>
<style>
	.Course-info, h2 {
		margin-top:2ch;
	}
</style>

GradeCalculator/Views/Grade/AddSemester.cshtml
@using GradeCalculator.ViewModel;
@model GradeViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@Model.profile.Name

GradeCalculator/Views/Grade/DeleteCourse.cshtml
@using GradeCalculator.ViewModel;
@model GradeViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<a class="btn btn-dark" asp-action="Index" asp-controller="Grade" asp-route-id="@Model.profile.ID">Back</a>
<h2>Deleted Course</h2>
<div class="Course-info">
	<p class="fs-5"><span class="fw-light">Code</span> @Model.newCourse.CourseCode</p>
	<p class="fs-5"><span class="fw-light">Title</span> @Model.newCourse.CourseTitle</p>
	<p class="fs-5"><span class="fw-light">Credit Hour</span> @Model.newCourse.CreditHour</p>
	<p class="fs-5"><span class="fw-light">Grade</span> @Model.newCourse.Grade</p>
	<p class="fs-5"><span class="fw-light">Grade Point</span> @Model.newCourse.GradePoint</p>
</div>
<style>
	.Course-info, h2 {
		margin-top: 2ch;
	}
</style>

GradeCalculator/Views/Grade/DeleteSemester.cshtml
@using GradeCalculator.ViewModel;
@model GradeViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<a class="btn btn-dark" asp-action="Index" asp-controller="Grade" asp-route-id="@Model.profile.ID">Back</a>
<h2>Deleted Semester</h2>
<div class="Semester-info">
	<p class="fs-5"><span class="fw-light">Semester Name</span> @Model.newSemester.Name</p>
	<p class="fs-5"><span class="fw-light">Semester Year</span> @Model.newSemester.Year</p>
	<p class="fs-5"><span class="fw-light">Semester Order</span> @Model.newSemester.SemesterOrder</p>
</div>

<style>
	.Semester-info, h2 {
		margin-top: 2ch;
	}
</style>

GradeCalculator/Views/Grade/EditCourse.cshtml
@using GradeCalculator.ViewModel;
@model GradeViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<a class="btn btn-dark" asp-action="Index" asp-controller="Grade" asp-route-id="@Model.profile.ID">Back</a>
@Model.newSemester.Id
<form enctype="multipart/form-data" method="post" class="AddCourseForm" asp-action="EditCourse" asp-controller="Grade">
	<div class="modal-body">
		<h3>Edit Course</h3>
		<input hidden asp-for="profile.ID" value="@Model.profile.ID">
		<input hidden asp-for="profile.Name" value="@Model.profile.Name">
		<input hidden asp-for="newSemester.Id" value="@Model.newSemester.Id">
		<input hidden asp-for="newCourse.Id" value="@Model.newCourse.Id">

		<label class="form-label text-left" asp-for="newCourse.CourseCode">Course Code</label>
		<input class="form-control" asp-for="newCourse.CourseCode" value="@Model.newCourse.CourseCode">

		<label class="form-label text-left" asp-for="newCourse.CourseTitle">Course Title</label>
		<input class="form-control" asp-for="newCourse.CourseTitle" value="@Model.newCourse.CourseTitle">

		<label class="form-label text-left" asp-for="newCourse.CreditHour">Credit Hour</label>
		<input class="form-control" asp-for="newCourse.CreditHour" value="@Model.newCourse.CreditHour">

		<label class="form-label text-left" asp-for="newCourse.Grade">Course Grade</label>
		<input class="form-control" asp-for="newCourse.Grade" value="@Model.newCourse.Grade">

		<label class="form-label text-left" asp-for="newCourse.GradePoint">Course Grade Point</label>
		<input class="form-control" asp-for="newCourse.GradePoint" value="@Model.newCourse.GradePoint">

	</div>
	<div class="modal-footer">
		<input type="submit" class="btn btn-primary" value="Save Changes">
	</div>
</form>

GradeCalculator/Views/Grade/EditSemester.cshtml
@using GradeCalculator.ViewModel;
@model GradeViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<a class="btn btn-dark" asp-action="Index" asp-controller="Grade" asp-route-id="@Model.profile.ID">Back</a>

<form enctype="multipart/form-data" method="post" class="AddCourseForm" asp-action="EditSemester" asp-controller="Grade">
	<div class="modal-body">
		<h3>Edit Semester</h3>
		<input hidden asp-for="profile.ID" value="@Model.profile.ID">
		<input hidden asp-for="profile.Name" value="@Model.profile.Name">
		<input hidden asp-for="newSemester.Id" value="@Model.newSemester.Id">
		
		<label class="form-label text-left" asp-for="newSemester.Name">Semester Name</label>
		<input class="form-control" asp-for="newSemester.Name" value="@Model.newSemester.Name">

		<label class="form-label text-left" asp-for="newSemester.Year">Semester Year</label>
		<input class="form-control" asp-for="newSemester.Year" value="@Model.newSemester.Year">

		<label class="form-label text-left" asp-for="newSemester.SemesterOrder">Semester Order</label>
		<input class="form-control" asp-for="newSemester.SemesterOrder" value="@Model.newSemester.SemesterOrder">
	</div>
	<div class="modal-footer">
		<input type="submit" class="btn btn-primary" value="Save Changes">
	</div>
</form>

GradeCalculator/Views/Grade/Index.cshtml
@using GradeCalculator.ViewModel;
@model GradeViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h4>
	@Model.profile.Name's Grades
</h4>
@if (Model.profile.Semesters != null && Model.profile.Semesters.Count > 0)
{
	<div class="semesters">
		@foreach (var s in Model.profile.Semesters)
		{
			<div class="semester">
				<div class="semester-name">
					Semester @s.Name (Order: @s.SemesterOrder, ID: @s.Id), @s.Year
				</div>
				<table class="Course-table w-100">
					<thead>
						<tr>
							<th>Course Code</th>
							<th>Course Title</th>
							<th>Credit Hour</th>
							<th>Grade</th>
							<th>Grade Point</th>
							<th>Edit</th>
							<th>Delete</th>
						</tr>
					</thead>
					<tbody>

						@if (s.Courses != null && s.Courses.Count > 0)
						{
							foreach (var c in s.Courses)
							{
								<tr>
									<td class="CourseCode">@c.CourseCode</td>
									<td class="CourseTitle">@c.CourseTitle</td>
									<td class="CreditHour">@c.CreditHour</td>
									<td class="CourseGrade">@c.Grade</td>
									<td class="GradePoint">@c.GradePoint</td>
									<td>
										<form method="post" enctype="multipart/form-data" asp-controller="Grade" asp-action="EditCourse">
											<input hidden asp-for="profile.ID" value="@Model.profile.ID">
											<input hidden asp-for="profile.Name" value="@Model.profile.Name">
											<input hidden asp-for="newCourse.Id" value="@c.Id">
											<input hidden asp-for="newSemester.Id" value="@s.Id">
											<button class="submit-buttons" type="submit"> <img src="~/edit.png"> </button>
										</form>
									</td>
									<td>
										<form method="post" enctype="multipart/form-data" asp-controller="Grade" asp-action="DeleteCourse">
											<input hidden asp-for="profile.ID" value="@Model.profile.ID">
											<input hidden asp-for="profile.Name" value="@Model.profile.Name">
											<input hidden asp-for="newCourse.Id" value="@c.Id">
											<input hidden asp-for="newSemester.Id" value="@s.Id">
											<button class="submit-buttons" type="submit"> <img src="~/trash.png"> </button>
										</form>
									</td>
								</tr>
							}
						}
						<tr>
							<td colspan="7">
								<!-- Button trigger modal -->
								<button type="button" class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#exampleModal-@s.Id">
									Add Course
								</button>

								<!-- Modal -->
								<div class="modal fade" id="exampleModal-@s.Id" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
									<div class="modal-dialog">
										<div class="modal-content">
											<div class="modal-header">
												<h5 class="modal-title" id="exampleModalLabel">Add Course</h5>
												<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
											</div>
											<form enctype="multipart/form-data" method="post" class="AddCourseForm" asp-action="AddCourse" asp-controller="Grade">
												<div class="modal-body">
													<input hidden asp-for="profile.ID" value="@Model.profile.ID">
													<input hidden asp-for="profile.Name" value="@Model.profile.Name">
													<input hidden asp-for="newSemester.Id" value="@s.Id">
													<label class="form-label text-left" asp-for="newCourse.CourseCode">Course Code</label>
													<input class="form-control" asp-for="newCourse.CourseCode">

													<label class="form-label" asp-for="newCourse.CourseTitle">Course Title</label>
													<input class="form-control" asp-for="newCourse.CourseTitle">

													<label class="form-label" asp-for="newCourse.CreditHour">Credit Hour</label>
													<input class="form-control" asp-for="newCourse.CreditHour">

													<label class="form-label" asp-for="newCourse.Grade">Grade</label>
													<input class="form-control" asp-for="newCourse.Grade">
												</div>
												<div class="modal-footer">
													<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
													<input type="submit" class="btn btn-primary" value="Save Changes">
												</div>
											</form>
										</div>
									</div>
								</div>
							</td>
						</tr>
					</tbody>
				</table>
				<div class="semester-bottom">
					<div class="GPA-Section">
						<div class="AverageGPA">
							Average GPA: @s.Average
						</div>
						<div class="CGPA">
							CGPA: @s.CGPA
						</div>
					</div>
					<div class="options-section">
						<form method="post" enctype="multipart/form-data" asp-controller="Grade" asp-action="DeleteSemester">
							<input hidden asp-for="profile.ID" value="@Model.profile.ID">
							<input hidden asp-for="profile.Name" value="@Model.profile.Name">
							<input hidden asp-for="newSemester.Id" value="@s.Id">
							<input type="submit" class="btn btn-danger" value="Delete">
						</form>
						<form method="post" enctype="multipart/form-data" asp-controller="Grade" asp-action="EditSemester">
							<input hidden asp-for="profile.ID" value="@Model.profile.ID">
							<input hidden asp-for="profile.Name" value="@Model.profile.Name">
							<input hidden asp-for="newSemester.Id" value="@s.Id">
							<input type="submit" class="btn btn-warning" value="Edit">
						</form>
					</div>
				</div>
			</div>
		}
	</div>
}
<div>
	<form class="AddSemester" method="post" enctype="multipart/form-data" asp-controller="Grade" asp-action="AddSemester">
		<h3>Add Semester Form</h3>
		<input hidden asp-for="profile.ID" value="@Model.profile.ID">
		<input hidden asp-for="profile.Name" value="@Model.profile.Name">
		<label asp-for="newSemester.Name">Semester Name</label>
		<input asp-for="newSemester.Name">
		<label asp-for="newSemester.Year">Semester Year</label>
		<input asp-for="newSemester.Year">
		<label asp-for="newSemester.SemesterOrder">Semester Order</label>
		<input asp-for="newSemester.SemesterOrder">
		<input type="submit" value="Save" class="AddSemester-submit">
	</form>
</div>
<style>
	img {
		width: 30px;
	}

	.submit-buttons {
		background-color:transparent;
		border:0px solid black;
	}

	.semesters {
		display: flex;
		flex-wrap: wrap;
		width: 100%;
	}

	.semester {
		
		flex-direction: column;
		align-items: center;
		justify-content: center;
		margin: 2ch;
		width: 68ch;
		border-radius: 15px;
		overflow: hidden;
	}

	.semester-name {
		color: white;
		width: 100%;
		height: 4ch;
		text-align: center;
		padding-top: 1ch;
		overflow: hidden;
		background-color: #415a77;
	}

	.semester-bottom {
		width: 100%;
		display: flex;
		justify-content: space-around;
		align-items: center;
		background-color: #415a77;
		color: white;
		height: 8ch;
	}

	.options-section {
		display: flex;
		flex-direction: row;
	}

		.options-section form {
			margin: 1ch;
		}

	.GPA-Section {
		text-align: left;
	}

	.Course-table {
		text-align: center;
	}

	th,
	td {
		padding: 7px;
		text-align: center;
	}

	.semester th {
		background-color: #778da9;
	}

	.semester td {
		background-color: #e0e1dd;
		border-bottom: 1px solid black;
		border-top: 1px solid black;
	}

	.AddSemester {
		display: flex;
		flex-direction: column;
		width: 50ch;
		background-color: #8ecae6;
		margin-inline: auto;
		padding: 3ch;
		padding-inline: 7ch;
		border-radius: 15px;
	}

		.AddSemester label {
			text-align: left;
			margin-top: 1ch;
			margin-bottom: 0.5ch;
		}

	.AddSemester-submit {
		margin: 2ch;
		margin-top: 3ch;
		margin-inline: auto;
		width: 20ch;
	}
</style>

GradeCalculator/Views/Grade/ViewGrades.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="semesters">
	<div class="semester">
		<div class="semester-name">
			Term Autumn
		</div>
		<table class="Course-table">
			<thead>

				<tr>
					<th>Course Code</th>
					<th>Course Title</th>
					<th>Credit Hour</th>
					<th>Grade</th>
					<th>Grade Point</th>
				</tr>
			</thead>
			<tbody>

				<tr>
					<td class="CourseCode">CS111</td>
					<td class="CourseTitle">Introduction to Computer Science</td>
					<td class="CreditHour">5</td>
					<td class="CourseGrade">A+</td>
					<td class="GradePoint">20</td>
				</tr>
				<tr>
					<td>CS111</td>
					<td>Introduction to Computer Science</td>
					<td>5</td>
					<td>A+</td>
					<td>20</td>
				</tr>
				<tr>
					<td>CS111</td>
					<td>Introduction to Computer Science</td>
					<td>5</td>
					<td>A+</td>
					<td>20</td>
				</tr>
			</tbody>
		</table>
		<div class="semester-bottom">
			<div class="GPA-Section">
				<div class="AverageGPA">
					Average GPA: 3.0
				</div>
				<div class="CGPA">
					CGPA: 3.0
				</div>
			</div>
			<div class="options-section">
				<form method="post">
					<input type="submit" value="Delete">
				</form>
				<form method="post">
					<input type="submit" value="Edit">
				</form>
			</div>
		</div>
	</div>

</div>

<style>
	.semesters {
		display: flex;
		flex-wrap: wrap;
		width: 100%;
	}

	.semester {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		margin: 2ch;
		width: 68ch;
		border-radius: 15px;
		overflow: hidden;
		background-color: #219ebc;
	}

	.semester-name {
		color: white;
		width: 100%;
		height: 4ch;
		text-align: center;
		padding-top: 1ch;
		overflow: hidden;
		background-color: #023047;
	}

	.semester-bottom {
		width: 100%;
		display: flex;
		justify-content: space-around;
		align-items: center;
		background-color: #8ecae6;
		height: 8ch;
	}

	.options-section {
		display: flex;
		flex-direction: row;
	}

		.options-section form {
			margin: 1ch;
		}

	.GPA-Section {
		text-align: left;
	}

	.Course-table {
		text-align: center;
	}

	th,
	td {
		padding: 7px;
		text-align: center;
	}
</style>

GradeCalculator/Views/Home/Index.cshtml
@using GradeCalculator.ViewModel;
@model ProfileViewModel
@{
	ViewData["Title"] = "Home Page";
}
@if (@Model.Profiles.Count > 0)
{
	<h3>
		Profiles
	</h3>
	<h4>Select Profile</h4>

	<div class="profile-container">
		@foreach (var p in @Model.Profiles)
		{
			<a class="profile" asp-controller="Grade" asp-action="Index" asp-route-id="@p.ID">
				@p.Name
			</a>
		}
	</div>
}

<form method="post" class="add-profile-form" asp-controller="Home" asp-action="AddProfile" enctype="multipart/form-data">
	<h4>
		Add Profile
	</h4>
	<div class="form-group ">
		<label asp-for="Profile.Name">Name</label>
		<input asp-for="Profile.Name" class="form-control" style="margin-top:1ch; margin-bottom:1ch;" id="ProfileName">
	</div>
	<input type="submit" value="Add Profile" class="add-profile">
</form>

<style>
	.profile {
		background-color: #fff;
		border-radius: 10px;
		padding: 20px;
		margin-bottom: 20px;
		width: 15ch;
		box-shadow: 0 0 10px rgba(0,0,0,0.15);
		margin-right: 3ch;
		margin-top: 2ch;
		margin-bottom: 1ch;
		text-decoration:none;
		text-align:center;
	}

		.profile:hover {
			background-color: #8ecae6;
		}

	.profile-container {
		display: flex;
		flex-wrap: wrap;
	}

	.add-profile-form {
		background-color: #8ecae6;
		width: 29vw;
		padding: 2ch;
		border-radius: 10px;
		margin-top: 3ch;
	}
</style>

GradeCalculator/Views/Home/ViewGrades.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="grade-body">
	<div class="semesters">
		<div class="semester">
			<div class="semester-name">
				Term Autumn
			</div>
			<table class="Course-table">
				<tr>
					<th>Course Code</th>
					<th>Course Title</th>
					<th>Credit Hour</th>
					<th>Grade</th>
					<th>Grade Point</th>
				</tr>
				<tr>
					<td class="CourseCode">CS111</td>
					<td class="CourseTitle">Introduction to Computer Science</td>
					<td class="CreditHour">5</td>
					<td class="CourseGrade">A+</td>
					<td class="GradePoint">20</td>
				</tr>
				<tr>
					<td>CS111</td>
					<td>Introduction to Computer Science</td>
					<td>5</td>
					<td>A+</td>
					<td>20</td>
				</tr>
				<tr>
					<td>CS111</td>
					<td>Introduction to Computer Science</td>
					<td>5</td>
					<td>A+</td>
					<td>20</td>
				</tr>
			</table>
			<div class="semester-bottom">
				<div class="GPA-Section">
					<div class="AverageGPA">
						Average GPA: 3.0
					</div>
					<div class="CGPA">
						CGPA: 3.0
					</div>
				</div>
				<div class="options-section">
					<form method="post">
						<input type="button" value="Delete">
					</form>
					<form method="post">
						<input type="button" value="Edit">
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<style>
	.grade-body {
		background-color: orange;
		font-family: 'Roboto', sans-serif;
	}

	.semesters {
		display: flex;
		flex-wrap: wrap;
		width: 100%;
	}

	.semester {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		margin: 2ch;
		width: 68ch;
		border-radius: 15px;
		overflow: hidden;
		background-color: #219ebc;
	}

	.semester-name {
		width: 100%;
		height: 4ch;
		text-align: center;
		padding-top: 1ch;
		overflow: hidden;
		background-color: #023047;
		color: white;
	}

	.semester-bottom {
		width: 100%;
		display: flex;
		justify-content: space-around;
		align-items: center;
		background-color: #8ecae6;
		height: 8ch;
	}

	.options-section {
		display: flex;
		flex-direction: row;
	}

		.options-section form {
			margin: 1ch;
		}

	.GPA-Section {
		text-align: left;
	}

	.Course-table {
		text-align: center;
	}

	th,
	td {
		padding: 7px;
		text-align: center;
	}
</style>